# Generated by Django 4.2.16 on 2024-12-16 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_review_rating'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='product',
            new_name='shop_produc_id_f21274_idx',
            old_fields=('id', 'slug'),
        ),
    ]
